### ISSUE TITLE
Ability to disable indentation

### ISSUE THREAD

**Issue by Ravencrow** [leafgarland/typescript-vim#104]
The indentation was changed in a previous PR, but that PR removed the ability to disable the indentation.

You only has to put the next lines on the `indent/typescript.vim` file, on line 4:

```
if get(g:, 'typescript_indent_disable')
   finish
endif
```

Thanks for your work with this plugin.

**Comment by leafgarland** [comment]
I would like to use the indent in https://github.com/pangloss/vim-javascript, with only small changes to work with the `typescript` filetype. If it does not have a toggle, that looks like a small enough change to add.
