### ISSUE TITLE
Problem with indentation of Promises

### ISSUE THREAD

**Issue by Ravencrow** [leafgarland/typescript-vim#105]
I'm using Promises and usually put the `.then()` and the `.catch()` in different lines than the invocation of the method returning the Promise. But the plugin is not indenting it correctly.

It should be:
```
this.aService.getAll()
  .then()
  .catch()
```

But actually it is:
```
this.aService.getAll()
.then()
.catch()
```

Thanks for the awesome plugin.

**Comment by Ravencrow** [comment]
I have seen that there is a PR that actually fix this, but it's frozen since the last year!

https://github.com/leafgarland/typescript-vim/pull/98

**Comment by leafgarland** [comment]
I have tried using the latest indent from pangloss/vim-javascript. It will indent as you have specified here but only if you add `0.` to `'indentkeys'`. It looks like there were various issues raised where people wanted the exact opposite of this issue and so they have settled on using `indentkeys`. I like this approach. What do you think?
