### ISSUE TITLE
Add how-to for compile on save to documentation

### ISSUE THREAD

**Issue by dubiousdavid** [leafgarland/typescript-vim#109]

**Comment by jessemillar** [comment]
Is this a simple .vimrc option? Or more in-depth?

**Comment by leafgarland** [comment]
While I'm open to discussion about adding this as a tip in the docs, it is really outside of the scope of this plugin. A quick web search will find articles about this, e.g. https://superuser.com/questions/269562/how-can-i-tell-vim-to-compile-a-document-on-save
