### ISSUE TITLE
0.9.x synx support

### ISSUE THREAD

**Issue by aoberoi** [leafgarland/typescript-vim#11]
I would love to see this vim plugin updated for the 0.9.x syntax enhancements.

**Comment by HerringtonDarkholme** [comment]
This time typescript 1.5 releases. Would you support es6 features and annotations?

**Comment by leafgarland** [comment]
Some of the newer features are supported now. Please let me know specific items which are not yet supported. Thanks.

**Comment by HerringtonDarkholme** [comment]
Thanks but I have already made my own fork https://github.com/HerringtonDarkholme/yats.vim

**Comment by leafgarland** [comment]
Oh, nice - that looks good.
