### ISSUE TITLE
Fold in every file after opened one ts file.

### ISSUE THREAD

**Issue by wizicer** [leafgarland/typescript-vim#113]
Once I opened a `ts` file, every file I open later would be fold to root level, even the file type is not `ts`.

**Comment by leafgarland** [comment]
I don't think there is anything in this plugin that sets fold related options, specifically the option `foldlevelstart` which controls the fold level when you edit a buffer.

If you enter `verbose set foldlevelstart` into the vim command window you should see where it was last set, that might help you track down what has changed it.
