### ISSUE TITLE
Syntax coloring not showing

### ISSUE THREAD

**Issue by sorakthunly** [leafgarland/typescript-vim#114]
This is my .vimrc

![image](https://cloud.githubusercontent.com/assets/19909685/24834030/201bd8d2-1d1d-11e7-9465-c800a5936a87.png)

It detects the file as being typescript but the color scheme isn't applied. So, I ended up with white foreground :/

![image](https://cloud.githubusercontent.com/assets/19909685/24834040/54372fae-1d1d-11e7-982d-2ce25306f503.png)

**Comment by Pr0duktiv** [comment]
Did you run `:PluginInstall`? After running the command, try restarting vim again. Worked for me

**Comment by TovrikTheThird** [comment]
I get the same thing as @sorakthunly does. PluginInstall works as expected:
![screen shot 2017-07-10 at 11 39 59 am](https://user-images.githubusercontent.com/3004955/28033929-9ba8744e-6564-11e7-8aac-a71d5235e792.png)

And still my text is all white but strangely with syntax highlighting for type keywords (boolean, string, etc)

**Comment by leafgarland** [comment]
@sorakthunly Your vimrc does not show any plugins being loaded. Check out vimplug for an easy to use vim plugin manager.

**Comment by leafgarland** [comment]
@TovrikTheThird I'm sorry you are seeing this issue - some others do too but I have not been able to reproduce. It is possibly related to the standard vim library setting a filetype for *.ts files. This typescript plugin should override that but it  does not always work.
