### ISSUE TITLE
Unknown function: TSOnBufEnter

### ISSUE THREAD

**Issue by mastertinner** [leafgarland/typescript-vim#115]
When opening a `.ts` file, I get the following error:

```txt
Error detected while processing BufEnter Auto commands for "*.ts":
E117: Unknown function: TSOnBufEnter
```

Everything still works but it's annoying getting these errors. If I disable `typescript-vim`, I don't get the error.

**Comment by leafgarland** [comment]
That's odd. There is no mention of that function in this plugin's code. Perhaps some interaction with another typescript plugin?

**Comment by mastertinner** [comment]
You're absolutely right, @leafgarland. The error seems to come from https://github.com/mhartington/nvim-typescript and not from your plugin. Sorry about that!
