### ISSUE TITLE
`:compiler! typescript` sets `&l:makeprg` instead of `&g:makeprg`

### ISSUE THREAD

**Issue by nelstrom** [leafgarland/typescript-vim#121]
From [`:help :compiler`](http://vimhelp.appspot.com/quickfix.txt.html#%3Acompiler):

> Without the "!" options are set for the current buffer.  With "!" global options are set.

When you run `:compiler typescript`, it should set buffer-local `makeprg` and `errorformat` options (this works fine).

When you run `:compiler! typescript`, it should set global `makeprg` and `errorformat` options. At the moment, `errorformat` gets set globally, but `makeprg` is only set locally.

As a solution, I suggest switching [this line](https://github.com/leafgarland/typescript-vim/blob/4dc79bd1b0c43c16cae146bee065f2acc6d2b789/compiler/typescript.vim#L18) to use `CompilerSet`.

**Comment by leafgarland** [comment]
Thanks for the bug report, and the PR!
