### ISSUE TITLE
Hashes (#) in template strings break syntax highlighting

### ISSUE THREAD

**Issue by drewschrauf-myob** [leafgarland/typescript-vim#137]
Using a `#` character in a template string breaks syntax highlighting for the rest of the file. Using a `#` inside a single/double quoted string is fine.

typescript-vim is sourced through the latest commit of https://github.com/sheerun/vim-polyglot/commit/a26134de3c09f9725667e14e7073a701bcff4e19.

![image](https://user-images.githubusercontent.com/17970832/40096334-c75ece96-5913-11e8-814d-17738b3ebd08.png)

**Comment by glacambre** [comment]
I have the same problem but I think it's not caused by typescript-vim (or vim-polyglot). When sourcing the plugin itself manually (e.g. `vim -u NORC -c "set rtp+=/tmp/typescript-vim"`), the problem doesn't seem to appear.
How do you load your plugins?

**Comment by glacambre** [comment]
Shougo found the issue in https://github.com/Shougo/dein.vim/issues/295#issuecomment-396035668 , the problem is that vim-polyglot loads the graphql syntax file.
The proposed fix is to add `let g:polyglot_disabled = ['graphql']` to your init.vim/vimrc before vim-polyglot is loaded.

**Comment by leafgarland** [comment]
Thanks for the info
