### ISSUE TITLE
Incorrect highlight in embedded jsx statement

### ISSUE THREAD

**Issue by heyrict** [leafgarland/typescript-vim#149]
When I embed a react component as a parameter to another react component, the following code will not be highlighted correctly.
Here is the example.
```typescript.tsx
class Test extends React.Component<ScreenProps, {}> {
  render() {
    return (
      <FlatList
          data={[{ key: "test", icon: <Icon style={APPICON} icon="test" /> }]}
 //                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//                                       This tag is not correctly parsed
          numColumns={4}
          horizontal={false}
          renderItem={({ item }) => (
            <View>
              {item.icon}
            </View>
          )}
      />
    )
  }
}
```
, and here is what I get.
![screenshot from 2018-08-28 14-57-01](https://user-images.githubusercontent.com/25698503/44705970-b61ce080-aad2-11e8-80b4-648fc21878c2.png)

Tested with db131b8 commit, 
vim version: `VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 08 2018 13:00:48)`

**Comment by cormacrelf** [comment]
Fixed in https://github.com/MaxMEllon/vim-jsx-pretty/pull/37, this isn't typescript-vim's fault.

**Comment by heyrict** [comment]
@cormacrelf Confirm fixed. Thank you so much!
