### ISSUE TITLE
Documentation: How to install

### ISSUE THREAD

**Issue by orefalo** [leafgarland/typescript-vim#16]
Could you provide more details about how to use Vundle for installation?
  I am no VIM experts, spf13-vim was trivial to install - i believe it is based on Vundle.

Thank you

**Comment by XiaodiKong** [comment]
but what must i add to .vimrc?  i install this plugin, but no use

**Comment by leafgarland** [comment]
If you have installed this plugin, e.g. with vim-plug, then you should see syntax highlighting when editing typescript files (*.ts/*.tsx).

You do not need to add anything to your .vimrc.
