### ISSUE TITLE
Multiline ternary indentation

### ISSUE THREAD

**Issue by MrGrinst** [leafgarland/typescript-vim#177]
Hey, thanks for an awesome library. I'm currently seeing an issue with multline ternary expressions. The indentation for lines after the ternary match the last line in the ternary rather than the base-line indentation of the expression.

Actual:
```
const str =
  condition
    ? 'condition'
    : 'not condition'
    
    typing new text...
```

Expected:
```
const str =
  condition
    ? 'condition'
    : 'not condition'

typing new text...
```

I'd be happy to dig into the code and push something up with a little direction on what a fix might look like.

**Comment by leafgarland** [comment]
Hello, as you have experienced my time for this repo is limited. If you are happy to take a look at this then I am very happy to accept any fixes.

Note the indent code is mostly taken from https://github.com/pangloss/vim-javascript, you might want to see if later changes their have already fixed this - then we can merge into this repo.
