### ISSUE TITLE
How to trigger autocomplete ?

### ISSUE THREAD

**Issue by MatthD** [leafgarland/typescript-vim#191]
For example if I write `import {} from "fs"` as in some editor I would want to use a shortcut (cmd+enter) to show alla available importable items, is there a way to do it ?

**Comment by JavierParra** [comment]
Autocomplete is not in the scope of this plugin.

The [README](https://github.com/leafgarland/typescript-vim#readme) directs you to [Tsuquyomi ](https://github.com/Quramy/tsuquyomi) for that.
