### ISSUE TITLE
Incorrect error highlighting.

### ISSUE THREAD

**Issue by musically-ut** [leafgarland/typescript-vim#35]
Examples: 

![Simple](http://i.imgur.com/mrYxZVP.png)

and

![Complicated](http://i.imgur.com/2MxAO1k.png?1)

Does this happen with someone else as well? Otherwise, is could be a strange interaction between plugins I have installed.

**Comment by leafgarland** [comment]
I don't think we can comment based on those screenshots, when I typed those code snippets in they looked good.

Do you have a small file that shows the problem?

**Comment by musically-ut** [comment]
This is aggravating. I didn't have a reproducible example and now it turns out that explicitly calling `:set filetype=typescript` actually fixes the problem. I'll have to investigate the messages more carefully to see which plugin is conflicting with the syntax highlighting.

I'll close this bug for now. Sorry for the inconvenience caused.

**Comment by leafgarland** [comment]
Ok. Cheers.
