### ISSUE TITLE
Unable to pass `--target` through g:typescript_compiler_options variable

### ISSUE THREAD

**Issue by bmenant** [leafgarland/typescript-vim#42]
Related to #29 and #25.

I’ve defined this compiler option in my `.vimrc`:
```
let g:typescript_compiler_options = '--target ES5' 
```  

Then, when I try to `:make`, the compiler didn’t run and displayed those notices instead:
```
:!make  2>&1| tee /tmp/jdoe/v5YcHTT/7
make: *** No targets specified and no makefile found.  Stop.
(1 of 1): make: *** No targets specified and no makefile found.  Stop. 
```

However, when I `:set makeprg=tsc\ --target\ ES5\ $*\ %`, the `:make` cmd works as expected.

EDIT: I’m also having those notices after commenting out the `g:typescript_compiler_options` definition.

N.B.: I’m also using the syntastic checker with `let g:syntastic_typescript_tsc_args = '--target ES5'` (which works fine). Could it be related?

**Comment by leafgarland** [comment]
I think something else is changing `makeprg` for your typescript buffer. If you enter this command in a typescript buffer you should see something like `tsc --target ES% $* %`.

    :echo &makeprg

**Comment by leafgarland** [comment]
I can't say if it is syntastic, I haven't tried that - you could try disabling it to find out.

**Comment by leafgarland** [comment]
I'm going to close this, assuming its related to other aspects of your vim setup. Happy to open it again if you have some more info.

**Comment by stefanpenner** [comment]
```
let g:syntastic_typescript_tsc_args = '--target ES5'
```

seems to work for me :)

**Comment by lvarayut** [comment]
I set `let g:typescript_compiler_options = '--target ES5'` inside my `.vimrc`. When I executed `:echo &makeprg`, I got `tsc --target ES5 $*  %`. 

However, I still got `Accessors are only available when targeting ECMAScript 5 and higher.`.

**Comment by leafgarland** [comment]
@lvarayut if you are using Syntastic then you could try changing `g:syntastic_typescript_tsc_args` as mentioned above. It looks like something else is compiling/checking your typescript code and not using `&makeprg`
