### ISSUE TITLE
"Decorators are only available when targeting ECMAScript 5 and higher" error on file save

### ISSUE THREAD

**Issue by yyyar** [leafgarland/typescript-vim#47]
I have an issue using typescript-vim with the typescript code containing decorators.
When I save file, I'm getting error:
error| TS1205: Decorators are only available when targeting ECMAScript 5 and higher.

I added `let g:typescript_compiler_options = '-t ES5 --module commonjs'` to my vimrc, but it does not help. When I run `:make` it works fine fine without errors, however.
Could you point me on what I'm missing?

P.S. I'm also using syntastic-async for pretty errors display.

![decorator](https://cloud.githubusercontent.com/assets/219061/7330245/9d37f29a-ea9f-11e4-88e2-e9075cae3f90.png)

Thanks!

**Comment by leafgarland** [comment]
I'm not sure but I think it is syntastic (or something else) that is giving you the error message when you save. This plugin does not do that, it only supports compiling via the `:make` command.

**Comment by leafgarland** [comment]
Looking at the docs for syntastic, I think you could do something like this to configure it:

    let g:syntastic_typescript_tsc_args = "--my --args --here"

**Comment by leafgarland** [comment]
Perhaps all these typescript plugins (including this one) should look at supporting [tsconfig.json](https://github.com/Microsoft/TypeScript/wiki/tsconfig.json)

**Comment by yyyar** [comment]
@leafgarland, Thank you, it works!

**Comment by myitcv** [comment]
@leafgarland :+1: to the comment about `tsconfig.json`

**Comment by metal3d** [comment]
:+1:  for syntastic option, that fixes my problem :)

**Comment by metal3d** [comment]
A better solution:
http://stackoverflow.com/questions/34102184/use-tsconfig-json-for-tsc-with-syntastic-in-vim

You only have to set this in .vimrc:
```vim
let g:syntastic_typescript_tsc_fname = ''
```
