### ISSUE TITLE
Can't install with NeoBundle

### ISSUE THREAD

**Issue by davidsteinberger** [leafgarland/typescript-vim#48]
I just tried installing this plugin via NeoBundle. However when I reload my *vimrc* I get cryptic errors:

    line    6:
    E492: Not an editor command: ^M
    line    7:
    E15: Invalid expression: !exists("main_syntax")^M

When I open up a *.tc* file the syntax highlighting doesn't work. The filetype is set to *typescript^M*.
Any idea what the issue may be?

**Comment by davidsteinberger** [comment]
I think it's the encoding of the *.vim files. When I convert them to unix everything works fine:
`find . -type f \( -iname "*.vim" \) -exec dos2unix {} \;`

**Comment by leafgarland** [comment]
Thanks for the info, I'll check if we have some bad line end encodings.

**Comment by barak-haviv** [comment]
Thanks. It worked for me
