### ISSUE TITLE
A way to disable launching compiler?

### ISSUE THREAD

**Issue by iwuvjhdva** [leafgarland/typescript-vim#50]
Writing a .js file in current folder is unnecessary functionality in real projects, normally you have a gulp task that does the compilation into a separate folder. Also the compilation with the plugin is really slow.

Maybe to provide a way to use the plugin without launching the compiler?

**Comment by leafgarland** [comment]
This plugin has no dependency on launching the compiler, or at least it should not have. 

It has options that allow you to launch the compiler via vim's `:make` command but those are easily changed to use something else. See vim docs for `:compiler` and `:make`.

**Comment by iwuvjhdva** [comment]
That's not true,
every time I save a .ts file it compiles it into JS and saves in current folder.
Is there any way to prevent this behaviour and to have just syntax highlighting and indent?
The generation of the JS file gives a lag on saving the file and is disturbing because of that.

**Comment by iwuvjhdva** [comment]
Sorry just realized that this behaviour was caused by Syntastic <3

**Comment by arnauddri** [comment]
Hi, 

I am experiencing the same issue. How did you solve this in the end? You just disabled syntastic for .ts files?

Many thanks

**Comment by iwuvjhdva** [comment]
Hi,
Not sure if I remember correctly, but I think this issue was related to Syntastic, not to typescript-vim.
Hope that helps.

**Comment by arnauddri** [comment]
ok thanks Ill look into this

2015-08-31 11:33 GMT+02:00 Konstantin Alexandrov <notifications@github.com>:
