### ISSUE TITLE
Is there a way to change colors of error? 

### ISSUE THREAD

**Issue by markogresak** [leafgarland/typescript-vim#60]
This is how it looks for me right now, because of my theme:

<img width="642" alt="screen shot 2015-08-02 at 03 15 30" src="https://cloud.githubusercontent.com/assets/6675751/9024257/6e191358-38c5-11e5-8240-f68ee042bdf1.png">

Is it possible to modify this without changing the theme?

**Comment by leafgarland** [comment]
I'm guessing that is the quickfix window in your screenshot, in which case this syntax does not have anything to do with those colours.

I think that background colour is using the `Search` highlight, the same as you would see if you searched for some text.

**Comment by leafgarland** [comment]
You might be able to change it by something like:

    :highlight Search guibg=<some-hex-colour> ctermbg=<some-cterm-color>
