### ISSUE TITLE
filetype bug

### ISSUE THREAD

**Issue by co-dh** [leafgarland/typescript-vim#64]
There is an annoying bug: after install this plugin, it will detect every file as typescript( .vim, gitcommit) etc.
I've figured it out that it has to do with Tsuquyomi.
Here is part of my .vimrc:

"NeoBundle Scripts-----------------------------
if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=/home/hao/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('/home/hao/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Add or remove your Bundles here:
" Essential
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'tomasr/molokai'

NeoBundle 'tpope/vim-unimpaired'
NeoBundle 'ctrlpvim/ctrlp.vim'
NeoBundle 'christoomey/vim-tmux-navigator'

"NeoBundle 'jiangmiao/auto-pairs'
"NeoBundle 'junegunn/vim-easy-align'
"NeoBundle 'easymotion/vim-easymotion'
NeoBundle 'bling/vim-airline'
"NeoBundle 'vim-scripts/dbext.vim'
"NeoBundle 'will133/vim-dirdiff'
"NeoBundle 'tmhedberg/SimpylFold'
NeoBundle 'Shougo/vimproc.vim', {'build' : {'linux' : 'make'}}
NeoBundle 'Quramy/tsuquyomi'
NeoBundle 'leafgarland/typescript-vim'
"NeoBundle 'pangloss/vim-javascript'
"NeoBundle 'mxw/vim-jsx'

"NeoBundle 'kchmck/vim-coffee-script'

"NeoBundle 'scrooloose/syntastic'

"NeoBundle "tmux-plugins/vim-tmux-focus-events"
"NeoBundle "blueyed/vim-diminactive"
"NeoBundle "davidoc/taskpaper.vim"
"NeoBundle "mattn/emmet-vim"

" disabled because of slow or other reason
"NeoBundle 'Valloric/YouCompleteMe'
"NeoBundle 'garbas/vim-snipmate'
"NeoBundle 'justinj/vim-react-snippets'
"NeoBundle 'Shougo/vimshell'
"NeoBundle 'klen/python-mode'

" Required:
call neobundle#end()

" Required:
filetype off
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck
"End NeoBundle Scripts-------------------------

Here is the step to reproduce:
1) open a tsx file ( typescript with react)
2) :Gst
3) you'll see that the git diff is detected as typescript file .

**Comment by co-dh** [comment]
Sorry, I figure it out that this bug belongs to tsuquyomi. I can reproduce it by have only tsuquyomi.
Please close it.

**Comment by leafgarland** [comment]
Ok, thanks for letting me know. Closed.
