### ISSUE TITLE
Syntax highlighting broken with spf13

### ISSUE THREAD

**Issue by amamut** [leafgarland/typescript-vim#69]
Syntax highlighting doesn't seem to autoload for ".ts" files when using [spf13-vim](http://vim.spf13.com/). If I run the `:set syntax=typescript` command with the file open it does load the highlighting so the plugin is install properly. I'm running a completely stock install of spf13 (within macvim) with the typescript-vim plugin installed via Vundle.

I can't seem to find why it's not working. Any help would be appreciated.

**Comment by msimpson** [comment]
I'm not getting highlighting for TypeScript files, regardless of their "ts" file extension. I was forced to add the following to my .vimrc: `autocmd BufNewFile,BufRead *.ts set syntax=typescript`

**Comment by leafgarland** [comment]
Hm, both these seem like file type detection issues. In this plugin file type detection is handled by `ftdetect/typescript.vim`, it contains a line very similar to @msimpson's autocmd.

Vim's auto filetype detection is enabled by `:filetype on'. You can check the current status by entering `:filetype`, you shoule see output like `filetype detection:ON plugin:ON indent:ON`

**Comment by msimpson** [comment]
@leafgarland 
My filetype detection was, and still is, enabled: `filetype detection:ON  plugin:ON  indent:ON` Yet, my autocmd line is still required.

**Comment by leafgarland** [comment]
Ok, good to know. Thanks for the update.

I'm going to close this, as it seems likely that any issues are in the vim setup rather than this plugin.

@amamut if you have more info, or more questions, I'm happy to try to help still.

**Comment by trichetriche** [comment]
I am re opening this issue since I have the same problem. Moving `syntax on` didn't resolve the issue for me, and the plugin doesn't highlight the syntax. Here is my .vimrc : 

    " Compatibility with the old Vi
    set nocompatible
    " Show line numbers
    set number

    filetype plugin indent on 

    " Vundle configuration
    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    " alternatively, pass a path where Vundle should install plugins
    "call vundle#begin('~/some/path/here')

    " let Vundle manage Vundle, required
    Plugin 'VundleVim/Vundle.vim'

    " NerdTree (file explorer)
    Plugin 'scrooloose/nerdtree'

    " CTRLP (qucik file open) 
    Plugin 'ctrlpvim/ctrlp.vim'

    " vim airline (pretty infos displays)
    Plugin 'vim-airline/vim-airline'
    Plugin 'vim-airline/vim-airline-themes'

    " vim autoclose (close parenthesis etc.)
    Plugin 'Townk/vim-autoclose'

    " Emmet (code completion) 
    Plugin 'mattn/emmet-vim'

    "Typescript for Vim
    Plugin 'leafgarland/typescript-vim'

    " All of your Plugins must be added before the following line
    call vundle#end()            " required
    filetype plugin indent on    " required

    " Auto launch vim NerdTree at vim startup
    autocmd VimEnter * NERDTree
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
    autocmd VimEnter * execute "normal \<C-w>w"

    syntax on

    " Indentation (set to 2 spaces here)
    set expandtab
    set shiftwidth=2
    set softtabstop=2
    " Smart indent : auto indent on caret return
    set smartindent
    " Enable mouse use
    set mouse=a
    " Set the split directions
    set splitright
    set splitbelow

    " shortcuts
    map <C-w>v :vnew<CR>
    map <C-w>s :new<CR>
    map <C-w><C-v> :vnew<CR>
    map <C-w><C-s> :new<CR>

    " change font for airline:
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1

    " CTRL-P ignore
    set wildignore+=*/node_modules/*
    let g:ctrlp_custom_ignore = 'node_modules'

    " set HTML auto-completion
    set omnifunc=htmlcomplete#CompleteTags

    " FZF for vim
    set rtp+=~/.fzf

**Comment by lcoenen** [comment]
Same issue here, and neovim try to xmlint my file (which of course doesn't work)

**Comment by sitecode** [comment]
This worked for me (in vim with an updated spf13) in my .vimrc.local:
`autocmd BufNewFile,BufRead *.ts set filetype=typescript`
The filetype needs to be set, which in turn will set syntax, and allow for proper linting, etc.
