### ISSUE TITLE
tsconfing config files not supported

### ISSUE THREAD

**Issue by jameslong** [leafgarland/typescript-vim#71]
It would be nice if there was an option to not pass the current file into the tsc build command. This way tsconfig files/alternative build methods could be supported. i.e. ```:make``` should only call: ```tsc```.

**Comment by leafgarland** [comment]
Copying a comment I made in #61.

> I think, rather than continue to add options like this it might better to override the `makeprg` setting in your own `.vimrc` or in `after/compiler/typescript.vim`.

> As an example, this in your `.vimrc` will achieve the same as this PR.

> ```vim
  autocmd FileType typescript call s:typescript_filetype_settings()
  function! s:typescript_filetype_settings()
    set makeprg=tsc
  endfunction
```

> With something like the above you have full control, and we don't need to keep adding options for different use cases.

Should add this to the readme.
