### ISSUE TITLE
QuickFix windows doesn't appear

### ISSUE THREAD

**Issue by idoo** [leafgarland/typescript-vim#77]
I reinstalled plugin and this window lost :(
Any ideas?

**Comment by leafgarland** [comment]
Does it appear when you enter `:copen`? If so then you mean that it doesn't automatically appear after you have used `:make`.

Have you added something like the this to your `.vimrc` to ask it to open?

```vim
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow
```
