### ISSUE TITLE
Error with Syntastic and outDir

### ISSUE THREAD

**Issue by dimascyriaco** [leafgarland/typescript-vim#78]
I'm getting the error "Option 'noEmit' cannot be specified with option 'outDir'" with Syntastic. I have this on my tsconfig.json:

```js
{
    "compilerOptions": {
        "target": "es6",
        "module": "amd",
        "outDir": "build",
        "sourceMap": true
    }
}
```

I imagine that Syntastic runs 'tsc' with the --noEmit tag, so the error.

Is there a way to make this work?

I've tried `let g:typescript_compiler_options = ''` but nothing.

**Comment by leafgarland** [comment]
That option will only affect the `makeprg` settings and I think Syntastic uses its own mechanisms to decide how to check files.

Perhaps check the source of the typescript checker in Syntastic https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/typescript/tsc.vim

**Comment by leafgarland** [comment]
Also see this in Syntastic docs
https://github.com/scrooloose/syntastic#faqargs
