### ISSUE TITLE
Not an editor command: CompilerSet

### ISSUE THREAD

**Issue by westandy** [leafgarland/typescript-vim#90]
Vim is not liking the CompilerSet command in compiler/typescript.vim, line 16

Any suggestions on fixing that?

**Comment by leafgarland** [comment]
Hi, the Vim docs suggest that older versions of Vim might not have the `CompilerSet` command, in which case this plugin should probably define it. I'll take a look at getting that added.

**Comment by leafgarland** [comment]
Fixed by 7e25a90

**Comment by westandy** [comment]
@leafgarland, I am now seeing this error:

Error detected while processing /home/awestmey/.vim/plugin/typescript-vim/ftplugin/typescript.vim:
line    9:
E174: Command already exists: add ! to replace it


So, I simply removed it.  I'm not sure if the plugin is working, though.

**Comment by leafgarland** [comment]
Thanks for the good report, I will take a look.

**Comment by leafgarland** [comment]
What version of vim are you using? I cannot recreate using your vimrc.
