### ISSUE TITLE
Highlighting of "const"

### ISSUE THREAD

**Issue by dbrgn** [leafgarland/typescript-vim#91]
The keywords `let` and `const` are highlighted differently:

![img](http://tmp.dbrgn.ch/screenshots/20160808130445-4qxjz8cl.png)

Could this be fixed somehow? Or is it intended? I think `const` should also be highlighted in cyan (like `let`).

**Comment by leafgarland** [comment]
Yes, I think you're right. It was listed in two different sets of keywords.

**Comment by dbrgn** [comment]
Great, thanks!
