### ISSUE TITLE
Is there any way to get the syntax highlighting without compiling on every write?

### ISSUE THREAD

**Issue by zacstewart** [leafgarland/typescript-vim#99]
It takes a second every time I write my file, and the quickfix buffer is more of a nuisance than a help. I'd prefer to just have highlighting and use Syntastic or something if I want error checking.

**Comment by leafgarland** [comment]
Are you sure that any file save actions are triggered by this plugin? That should not be happening.

**Comment by zacstewart** [comment]
You're absolutely right, my apologies. I forgot that I had installed tsuquyomi at the same time.
